spring:

  datasource:
    url: jdbc:postgresql://localhost:5435/osc_assistant
    username: test
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
